<?php

namespace AppBundle\Repository;

/**
 * ShipDestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipDestinationRepository extends \Doctrine\ORM\EntityRepository
{
}
