# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    appbundle.people.handler:
        class: AppBundle\Service\PeopleXmlHandler
        arguments: ['@doctrine.orm.entity_manager', '@jms_serializer']

    appbundle.order.handler:
        class: AppBundle\Service\OrdersXmlHandler
        arguments: ['@doctrine.orm.entity_manager', '@jms_serializer']
